######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 16 16:29:17 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h
SOURCES += main.cpp MainWindow.cpp
