#############################################################################
# Makefile for building: SimpleMapEditor.app/Contents/MacOS/SimpleMapEditor
# Generated by qmake (2.01a) (Qt 4.5.3) on: ?? ???. 30 00:50:54 2009
# Project:  SimpleMapEditor.pro
# Template: app
# Command: /opt/local/bin/qmake -spec /opt/local/libexec/qt4-mac/mkspecs/macx-xcode -macx -o SimpleMapEditor.xcodeproj/project.pbxproj SimpleMapEditor.pro
#############################################################################

QMAKE    = /opt/local/bin/qmake
SimpleMapEditor.xcodeproj/project.pbxproj: SimpleMapEditor.pro  /opt/local/libexec/qt4-mac/mkspecs/macx-xcode/qmake.conf /opt/local/libexec/qt4-mac/mkspecs/common/unix.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac.conf \
		/opt/local/libexec/qt4-mac/mkspecs/common/mac-g++.conf \
		/opt/local/libexec/qt4-mac/mkspecs/qconfig.pri \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_functions.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt_config.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/exclusive_builds.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_pre.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/dwarf2.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/debug.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_post.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/x86_64.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/objective_c.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/warn_on.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/qt.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/unix/thread.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/moc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/rez.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/mac/sdk.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/resources.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/uic.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/yacc.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/lex.prf \
		/opt/local/libexec/qt4-mac/mkspecs/features/include_source_dir.prf \
		/opt/local/libexec/qt4-mac/lib/QtXml.framework/QtXml.prl \
		/opt/local/libexec/qt4-mac/lib/QtCore.framework/QtCore.prl \
		/opt/local/libexec/qt4-mac/lib/QtGui.framework/QtGui.prl
	$(QMAKE) -spec /opt/local/libexec/qt4-mac/mkspecs/macx-xcode -macx -o SimpleMapEditor.xcodeproj/project.pbxproj SimpleMapEditor.pro
/opt/local/libexec/qt4-mac/mkspecs/common/unix.conf:
/opt/local/libexec/qt4-mac/mkspecs/common/mac.conf:
/opt/local/libexec/qt4-mac/mkspecs/common/mac-g++.conf:
/opt/local/libexec/qt4-mac/mkspecs/qconfig.pri:
/opt/local/libexec/qt4-mac/mkspecs/features/qt_functions.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/qt_config.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/exclusive_builds.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/default_pre.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_pre.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/dwarf2.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/debug.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/default_post.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/default_post.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/x86_64.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/objective_c.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/warn_on.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/qt.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/unix/thread.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/moc.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/rez.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/mac/sdk.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/resources.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/uic.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/yacc.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/lex.prf:
/opt/local/libexec/qt4-mac/mkspecs/features/include_source_dir.prf:
/opt/local/libexec/qt4-mac/lib/QtXml.framework/QtXml.prl:
/opt/local/libexec/qt4-mac/lib/QtCore.framework/QtCore.prl:
/opt/local/libexec/qt4-mac/lib/QtGui.framework/QtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/local/libexec/qt4-mac/mkspecs/macx-xcode -macx -o SimpleMapEditor.xcodeproj/project.pbxproj SimpleMapEditor.pro

