## Generated by rbison version 0.0.7.

class RParser

    class ParseError < StandardError ; end
    class LexError < StandardError ; end
    NULL = nil

    attr :yydebug, true
    attr :yyerror, true

    SMALL_STR = 258
    BIG_STR = 259
    ENTER_S = 260
    END_S = 261
    ZAP = 262
    RULE_NEXT = 263
    DOT_ZAP = 264
    DOT = 265
    QUESTION = 266
	
    ## Parser declarations begin
    attr_reader :targets
    def init_data
    	@targets = Array.new
    end
    class Target
    	attr_reader :name, :params
    	def to_s
    		"Target: '"+@name+"' with '"+@params.join("', '")+"'"
    	end
    	def initialize( name, params )
    		@name, @params = name, params
    	end
    end
    #ifndef YYLTYPE
    typedef
      struct yyltype
        {
          int timestamp;
          int first_line;
          int first_column;
          int last_line;
          int last_column;
          char *text;
       }
      yyltype;
    #define YYLTYPE yyltype
    #endif
    ## Parser declarations end

    YYFINAL = 23
    YYFLAG = -32768
    YYNTBASE = 12
    YYTRANSLATE = [ 0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11
    ]
    YYPRHS = [ 0,
     0,     1,     4,     6,    10,    12,    17,    21,    23,    25,
    27,    29,    31,    33,    35
    ]
    YYRHS = [ -1,
    13,    12,     0,    14,     0,    14,     9,    15,     0,    15,
     0,    19,     5,    16,     6,     0,    16,     7,    17,     0,
    17,     0,    11,     0,    18,     0,    21,     0,    20,     0,
     4,     0,     4,     0,     3,     0
    ]
    YYRLINE = [ 0,
    32,    33,    36,    40,    42,    47,    56,    58,    63,    64,
    68,    69,    73,    77,    81
    ]
    YYTNAME = [ "$","error","$undefined.","SMALL_STR",
"BIG_STR","ENTER_S","END_S","ZAP","RULE_NEXT","DOT_ZAP","DOT","QUESTION","input",
"target","target_term_list","target_term","target_parameter_list","target_parameter_name",
"parameter_name","predicate_name","variable_name","const_name",""
    ]
    YYR1 = [ 0,
    12,    12,    13,    14,    14,    15,    16,    16,    17,    17,
    18,    18,    19,    20,    21
    ]
    YYR2 = [ 0,
     0,     2,     1,     3,     1,     4,     3,     1,     1,     1,
     1,     1,     1,     1,     1
    ]
    YYDEFACT = [ 1,
    13,     1,     3,     5,     0,     2,     0,     0,     4,    15,
    14,     9,     0,     8,    10,    12,    11,     6,     0,     7,
     0,     0,     0
    ]
    YYDEFGOTO = [ 6,
     2,     3,     4,    13,    14,    15,     5,    16,    17
    ]
    YYPACT = [ 0,
-32768,     0,    -2,-32768,     1,-32768,     0,    -3,-32768,-32768,
-32768,-32768,    -4,-32768,-32768,-32768,-32768,-32768,    -3,-32768,
     5,     9,-32768
    ]
    YYPGOTO = [ 10,
-32768,-32768,     4,-32768,    -7,-32768,-32768,-32768,-32768
    ]
    YYLAST = 12
    YYTABLE = [ 10,
    11,    18,    19,     1,    22,     8,     7,    12,    23,    21,
     9,    20
    ]
    YYCHECK = [ 3,
     4,     6,     7,     4,     0,     5,     9,    11,     0,     0,
     7,    19
    ]
    YYEMPTY = -2
    YYEOF = 0
    YYTERROR = 1
    
    def initialize
	@yyerror = $stderr
	@yydebug = false
    end
    
    def yyparse(lexer)
	yyerrstatus = 0
	yychar = YYEMPTY
	yystate = 0
	yyss = []
	yyvs = ["nil"]
	yyval = 0
	jump = :YYNEWSTATE

	while true
	    
	    case jump
	
	    when :YYNEWSTATE
		if @yydebug
		    printf(@yyerror, "Entering state %d\n", yystate)
		end
		yyss.push(yystate)
		jump = :YYBACKUP
		next
	
	    when :YYBACKUP
		yyn = YYPACT[yystate]
		if yyn == YYFLAG
		    jump = :YYDEFAULT
		    next
		end
	
		## get a lookahead token if we don't already have one
		if yychar == YYEMPTY
		    if @yydebug
			printf(@yyerror, "Reading a token: ")
		    end
		    begin
			yychar, yylval = lexer.yylex
# sidorovis debug info
#			puts yylval
		    rescue LexError
			raise ParseError, "lex error"
		    end
		end
	
		## if lookahead <= 0, end of input
		if yychar <= 0
		    yychar1 = 0
		    yychar = YYEOF
		    if @yydebug
			printf(@yyerror, "Now at end of input.\n")
		    end
		else
		    yychar1 = yychar < 0 || yychar > 266 ? 22 : YYTRANSLATE[yychar]
		    if @yydebug
			printf(@yyerror, "Next token is %d (%s,%s)\n", yychar,
			       YYTNAME[yychar1], yylval)
		    end
		end
	
		## see if we know what to do with this token in this state
		yyn += yychar1
		if yyn < 0 || yyn > YYLAST || YYCHECK[yyn] != yychar1
		    jump = :YYDEFAULT
		    next
		end
	
		## yyn is what to do for this token type in this state
		## negative -> reduce, - yyn is the rule number
		## positive -> shift, yyn is the new state
		##    New state is final state, don't bother to shift, just
		##    return success
		## 0, or most negative number -> error
		yyn = YYTABLE[yyn]
		if yyn < 0
		    if yyn == YYFLAG
			jump = :YYERRLAB
			next
		    end
		    yyn = - yyn
		    jump = :YYREDUCE
		    next
		elsif yyn == 0
		    jump = :YYERRLAB
		    next
		end
	    
		if yyn == YYFINAL
		    return ## accept
		end
	   
		## shift the lookahead token
		if @yydebug
		    printf(@yyerror, "Shifting token %d (%s), ", yychar,
			   YYTNAME[yychar1])
		end
		
		## discard the token being shifted unless it is eof
		if yychar != YYEOF
		    yychar = YYEMPTY
		end
		yyvs.push(yylval)
		
		## count tokens shifted since error; after, three turn off
		## error status
		yyerrstatus -= 1 if yyerrstatus > 0

		yystate = yyn
		jump = :YYNEWSTATE
		next
	
	    when :YYDEFAULT
		yyn = YYDEFACT[yystate]
		if yyn == 0
		    jump = :YYERRLAB
		    next
		else
		    jump = :YYREDUCE
		    next
		end
	
		## do a reduction. yyn is the number of the rule to reduce with
	    when :YYREDUCE
		yylen = YYR2[yyn]
		if yylen > 0
		    yyval = yyvs[yyvs.size - yylen]
		end
		
		if @yydebug
		    printf(@yyerror, "Reducing via rule %d (line %d), ", yyn,
			   YYRLINE[yyn])
		    i = YYPRHS[yyn]
		    while YYRHS[i] > 0
			printf(@yyerror, "%s ", YYTNAME[YYRHS[i]])
			i += 1
		    end
		    printf(@yyerror, " -> %s\n", YYTNAME[YYR1[yyn]])
		end
	
		case yyn
		when 4
		    	yyval = yyvs[-3].push( yyvs[-1] )   
		when 5
		    	yyval = [ yyvs[-1] ]  
		when 6
		     
		    yyval = [ yyvs[-4], yyvs[-2] ] 
		    @targets.push( Target.new(yyvs[-4], yyvs[-2]) )
		    
		when 7
		    	yyval = yyvs[-3].push( yyvs[-1] )   
		when 8
		    	yyval = [ yyvs[-1] ]   
		when 13
		     predicate_name = yylval
		when 14
		     variable_name = yylval
		when 15
		     const_name = yylval
		when -65536 ## never used, placeholder for ruby
		end
		
		if yylen > 0
		    yyss[(yyss.size - yylen) .. (yyss.size - 1)] = []
		    yyvs[(yyvs.size - yylen) .. (yyvs.size - 1)] = []
		end
		
		yyvs.push(yyval)
	
		if @yydebug
		    printf(@yyerror, "State stack now: %s\n", yyss.join(' '))
		    printf(@yyerror, "Value stack now: %s\n", yyvs.join(' '))
		end
		
		## "Shift" the result of the reduction.
		yyn = YYR1[yyn]
		yystate = YYPGOTO[yyn - YYNTBASE] + yyss[-1]
		if yystate >=0 && yystate <= YYLAST &&
			YYCHECK[yystate] == yyss[-1]
		    yystate = YYTABLE[yystate]
		else
		    yystate = YYDEFGOTO[yyn - YYNTBASE]
		end
		jump = :YYNEWSTATE
		next
	
	    when :YYERRLAB
		if yyerrstatus == 0 && @yydebug
		    printf(@yyerror, "Parse error!\n")
		end
		jump = :YYERRLAB1
		next
		
	    when :YYERRLAB1
		if yyerrstatus == 3
		    if yychar == YYEOF
			raise ParseError, "parse error"
		    end
		    if @yydebug
			printf(@yyerror, "Discarding token %d (%s).\n", yychar,
			       YYTNAME[yychar1])
		    end
		    yychar = YYEMPTY
		end
	    
		yyerrstatus = 3
		jump = :YYERRHANDLE
		next

	    when :YYERRPOP
		if yyvs.empty?
		    raise ParseError, "parse error"
		end
		## don't pop if the state on top of the stack can handle
		## the error token
		yystate = yyss[-1]
		if YYCHECK[YYPACT[yystate] + YYTERROR] != YYTERROR
		    yyvs.pop
		    yyss.pop
		    if @yydebug
			printf(@yyerror, "Error: state stack now: %s\n",
			       yyss.join(' '))
			printf(@yyerror, "Error: Value stack now: %s\n",
			       yyvs.join(' '))
		    end
		end
		jump = :YYERRHANDLE
		next

	    when :YYERRHANDLE
		yyn = YYPACT[yystate]
		if yyn == YYFLAG
		    jump = :YYERRPOP
		    next
		end

		yyn += YYTERROR
		if yyn < 0 || yyn > YYLAST || YYCHECK[yyn] != YYTERROR
		    jump = :YYERRPOP
		    next
		end
    
		yyn = YYTABLE[yyn]
		if yyn < 0
		    if yyn == YYFLAG
			jump = :YYERRPOP
			next
		    end
		    yyn = -yyn
		    jump = :YYREDUCE
		    next
		elsif yyn == 0
		    jump = :YYERRPOP
		    next
		end
    
		if yyn == YYFINAL
		    return ## accept
		end
    
		if @yydebug
		    printf(@yyerror, "Shifting error token, ")
		end
    
		yyvs.push(yylval)
		yystate = yyn
		jump = :YYNEWSTATE
		next
		
	    end ## case
	    
	end ## while true
	
    end ## yyparse

end ## class

## Additional user code
