## Generated by rbison version 0.0.7.

class Parser

    class ParseError < StandardError ; end
    class LexError < StandardError ; end
    NULL = nil

    attr :yydebug, true
    attr :yyerror, true

    SMALL_STR = 258
    BIG_STR = 259
    ENTER_S = 260
    END_S = 261
    ZAP = 262
    RULE_NEXT = 263
    DOT_ZAP = 264
	

    YYFINAL = 54
    YYFLAG = -32768
    YYNTBASE = 10
    YYTRANSLATE = [ 0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9
    ]
    YYPRHS = [ 0,
     0,     1,     4,     6,     8,    10,    13,    15,    18,    20,
    22,    27,    30,    32,    34,    40,    46,    50,    52,    56,
    58,    62,    67,    69,    73,    75,    77,    79,    81,    83
    ]
    YYRHS = [ -1,
    10,    11,     0,    12,     0,    13,     0,    14,     0,    14,
    12,     0,    20,     0,    20,    13,     0,    15,     0,    16,
     0,    26,     5,    21,     6,     0,    29,    17,     0,    18,
     0,    19,     0,     5,    26,     7,    26,     6,     0,     5,
    28,     7,    28,     6,     0,    23,     8,    22,     0,    28,
     0,    21,     7,    28,     0,    23,     0,    22,     9,    23,
     0,    26,     5,    24,     6,     0,    25,     0,    24,     7,
    25,     0,    28,     0,    27,     0,     4,     0,     4,     0,
     3,     0,     3,     0
    ]
    YYRLINE = [ 0,
    17,    18,    21,    22,    26,    27,    31,    32,    36,    37,
    41,    45,    49,    50,    54,    58,    62,    66,    67,    71,
    72,    76,    80,    81,    85,    86,    90,    94,    98,   102
    ]
    YYTNAME = [ "$","error","$undefined.","SMALL_STR",
"BIG_STR","ENTER_S","END_S","ZAP","RULE_NEXT","DOT_ZAP","input","bz","fact_list",
"rule_list","fact1","predicate_fact","equal","pair_equal_names","pair_predicate_names",
"pair_const_names","rule","const_list","predicate_term_list","predicate_term",
"parameter_list","parameter_name","predicate_name","variable_name","const_name",
"equal_name",""
    ]
    YYR1 = [ 0,
    10,    10,    11,    11,    12,    12,    13,    13,    14,    14,
    15,    16,    17,    17,    18,    19,    20,    21,    21,    22,
    22,    23,    24,    24,    25,    25,    26,    27,    28,    29
    ]
    YYR2 = [ 0,
     0,     2,     1,     1,     1,     2,     1,     2,     1,     1,
     4,     2,     1,     1,     5,     5,     3,     1,     3,     1,
     3,     4,     1,     3,     1,     1,     1,     1,     1,     1
    ]
    YYDEFACT = [ 1,
     0,    30,    27,     2,     3,     4,     5,     9,    10,     7,
     0,     0,     0,     6,     0,     8,     0,     0,     0,     0,
    12,    13,    14,     0,     0,    17,    20,    29,    28,     0,
     0,    23,    26,    18,     0,     0,    18,    25,     0,    11,
     0,    22,     0,     0,     0,    21,    19,    24,     0,     0,
    15,    16,     0,     0
    ]
    YYDEFGOTO = [ 1,
     4,     5,     6,     7,     8,     9,    21,    22,    23,    10,
    30,    26,    11,    31,    32,    17,    33,    38,    13
    ]
    YYPACT = [ -32768,
     5,-32768,-32768,-32768,-32768,-32768,     7,-32768,-32768,    -3,
    15,    13,    17,-32768,    21,-32768,    22,    -3,     9,    11,
-32768,-32768,-32768,    26,     9,    23,-32768,-32768,-32768,    10,
    14,-32768,-32768,-32768,    24,    27,-32768,-32768,    -3,-32768,
    26,-32768,     9,    -3,    26,-32768,-32768,-32768,    29,    30,
-32768,-32768,    33,-32768
    ]
    YYPGOTO = [ -32768,
-32768,    31,    20,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,-32768,   -14,-32768,    -6,    -1,-32768,   -17,-32768
    ]
    YYLAST = 43
    YYTABLE = [ 12,
     3,    34,    36,    27,    53,    15,    37,     2,     3,     2,
     3,    28,    29,    28,     3,    40,    41,    19,    35,    42,
    43,    20,    18,    47,    46,    24,    25,    50,    28,    16,
    44,    39,    54,    45,    51,    52,    48,    14,     0,     0,
     0,     0,    49
    ]
    YYCHECK = [ 1,
     4,    19,    20,    18,     0,     7,    24,     3,     4,     3,
     4,     3,     4,     3,     4,     6,     7,     5,    20,     6,
     7,     5,     8,    41,    39,     5,     5,    45,     3,    10,
     7,     9,     0,     7,     6,     6,    43,     7,    -1,    -1,
    -1,    -1,    44
    ]
    YYEMPTY = -2
    YYEOF = 0
    YYTERROR = 1
    
    def initialize
	@yyerror = $stderr
	@yydebug = false
    end
    
    def yyparse(lexer)
	yyerrstatus = 0
	yychar = YYEMPTY
	yystate = 0
	yyss = []
	yyvs = ["nil"]
	yyval = 0
	jump = :YYNEWSTATE

	while true
	    
	    case jump
	
	    when :YYNEWSTATE
		if @yydebug
		    printf(@yyerror, "Entering state %d\n", yystate)
		end
		yyss.push(yystate)
		jump = :YYBACKUP
		next
	
	    when :YYBACKUP
		yyn = YYPACT[yystate]
		if yyn == YYFLAG
		    jump = :YYDEFAULT
		    next
		end
	
		## get a lookahead token if we don't already have one
		if yychar == YYEMPTY
		    if @yydebug
			printf(@yyerror, "Reading a token: ")
		    end
		    begin
			yychar, yylval = lexer.yylex
		    rescue LexError
			raise ParseError, "lex error"
		    end
		end
	
		## if lookahead <= 0, end of input
		if yychar <= 0
		    yychar1 = 0
		    yychar = YYEOF
		    if @yydebug
			printf(@yyerror, "Now at end of input.\n")
		    end
		else
		    yychar1 = yychar < 0 || yychar > 264 ? 30 : YYTRANSLATE[yychar]
		    if @yydebug
			printf(@yyerror, "Next token is %d (%s,%s)\n", yychar,
			       YYTNAME[yychar1], yylval)
		    end
		end
	
		## see if we know what to do with this token in this state
		yyn += yychar1
		if yyn < 0 || yyn > YYLAST || YYCHECK[yyn] != yychar1
		    jump = :YYDEFAULT
		    next
		end
	
		## yyn is what to do for this token type in this state
		## negative -> reduce, - yyn is the rule number
		## positive -> shift, yyn is the new state
		##    New state is final state, don't bother to shift, just
		##    return success
		## 0, or most negative number -> error
		yyn = YYTABLE[yyn]
		if yyn < 0
		    if yyn == YYFLAG
			jump = :YYERRLAB
			next
		    end
		    yyn = - yyn
		    jump = :YYREDUCE
		    next
		elsif yyn == 0
		    jump = :YYERRLAB
		    next
		end
	    
		if yyn == YYFINAL
		    return ## accept
		end
	   
		## shift the lookahead token
		if @yydebug
		    printf(@yyerror, "Shifting token %d (%s), ", yychar,
			   YYTNAME[yychar1])
		end
		
		## discard the token being shifted unless it is eof
		if yychar != YYEOF
		    yychar = YYEMPTY
		end
		yyvs.push(yylval)
		
		## count tokens shifted since error; after, three turn off
		## error status
		yyerrstatus -= 1 if yyerrstatus > 0

		yystate = yyn
		jump = :YYNEWSTATE
		next
	
	    when :YYDEFAULT
		yyn = YYDEFACT[yystate]
		if yyn == 0
		    jump = :YYERRLAB
		    next
		else
		    jump = :YYREDUCE
		    next
		end
	
		## do a reduction. yyn is the number of the rule to reduce with
	    when :YYREDUCE
		yylen = YYR2[yyn]
		if yylen > 0
		    yyval = yyvs[yyvs.size - yylen]
		end
		
		if @yydebug
		    printf(@yyerror, "Reducing via rule %d (line %d), ", yyn,
			   YYRLINE[yyn])
		    i = YYPRHS[yyn]
		    while YYRHS[i] > 0
			printf(@yyerror, "%s ", YYTNAME[YYRHS[i]])
			i += 1
		    end
		    printf(@yyerror, " -> %s\n", YYTNAME[YYR1[yyn]])
		end
	
		case yyn
		when -65536 ## never used, placeholder for ruby
		end
		
		if yylen > 0
		    yyss[(yyss.size - yylen) .. (yyss.size - 1)] = []
		    yyvs[(yyvs.size - yylen) .. (yyvs.size - 1)] = []
		end
		
		yyvs.push(yyval)
	
		if @yydebug
		    printf(@yyerror, "State stack now: %s\n", yyss.join(' '))
		    printf(@yyerror, "Value stack now: %s\n", yyvs.join(' '))
		end
		
		## "Shift" the result of the reduction.
		yyn = YYR1[yyn]
		yystate = YYPGOTO[yyn - YYNTBASE] + yyss[-1]
		if yystate >=0 && yystate <= YYLAST &&
			YYCHECK[yystate] == yyss[-1]
		    yystate = YYTABLE[yystate]
		else
		    yystate = YYDEFGOTO[yyn - YYNTBASE]
		end
		jump = :YYNEWSTATE
		next
	
	    when :YYERRLAB
		if yyerrstatus == 0 && @yydebug
		    printf(@yyerror, "Parse error!\n")
		end
		jump = :YYERRLAB1
		next
		
	    when :YYERRLAB1
		if yyerrstatus == 3
		    if yychar == YYEOF
			raise ParseError, "parse error"
		    end
		    if @yydebug
			printf(@yyerror, "Discarding token %d (%s).\n", yychar,
			       YYTNAME[yychar1])
		    end
		    yychar = YYEMPTY
		end
	    
		yyerrstatus = 3
		jump = :YYERRHANDLE
		next

	    when :YYERRPOP
		if yyvs.empty?
		    raise ParseError, "parse error"
		end
		## don't pop if the state on top of the stack can handle
		## the error token
		yystate = yyss[-1]
		if YYCHECK[YYPACT[yystate] + YYTERROR] != YYTERROR
		    yyvs.pop
		    yyss.pop
		    if @yydebug
			printf(@yyerror, "Error: state stack now: %s\n",
			       yyss.join(' '))
			printf(@yyerror, "Error: Value stack now: %s\n",
			       yyvs.join(' '))
		    end
		end
		jump = :YYERRHANDLE
		next

	    when :YYERRHANDLE
		yyn = YYPACT[yystate]
		if yyn == YYFLAG
		    jump = :YYERRPOP
		    next
		end

		yyn += YYTERROR
		if yyn < 0 || yyn > YYLAST || YYCHECK[yyn] != YYTERROR
		    jump = :YYERRPOP
		    next
		end
    
		yyn = YYTABLE[yyn]
		if yyn < 0
		    if yyn == YYFLAG
			jump = :YYERRPOP
			next
		    end
		    yyn = -yyn
		    jump = :YYREDUCE
		    next
		elsif yyn == 0
		    jump = :YYERRPOP
		    next
		end
    
		if yyn == YYFINAL
		    return ## accept
		end
    
		if @yydebug
		    printf(@yyerror, "Shifting error token, ")
		end
    
		yyvs.push(yylval)
		yystate = yyn
		jump = :YYNEWSTATE
		next
		
	    end ## case
	    
	end ## while true
	
    end ## yyparse

end ## class

## Additional user code
